import type {Metadata} from 'next'
import './globals.css'
import React from "react";
import {roboto} from "@/assets/fonts";
import {cn} from "@/lib/utils";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={cn(roboto.className)}>
        <Header/>
        <main className="flex-grow pt-[52px]">{children}</main>
        <Footer/>
        </body>
        </html>
    )
}
